// Thin re-export from the source-of-truth `@unif/react-native-design` icons barrel.
// `src/icons/data.ts` is auto-generated by `scripts/build-icons.js`;
// keeping this file as a re-export keeps backward-compat for any existing
// `./iconsCatalog` consumers while always serving the latest catalog.
export { ICONS, ICON_NAMES } from '@unif/react-native-design';
export type { IconDef, IconElement, IconName } from '@unif/react-native-design';
